# Generated by Django 3.2.12 on 2023-02-21 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('instructions', models.TextField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('filename_url', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(max_length=80, null=True)),
                ('ingredients', models.ManyToManyField(to='ingredients.Ingredient')),
            ],
        ),
    ]
