# Generated by Django 3.2.12 on 2022-04-12 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('name', models.CharField(max_length=80)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('title', models.CharField(max_length=80)),
                ('instructions', models.CharField(max_length=80)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('ingredients', models.ManyToManyField(to='recipes.Ingredient')),
            ],
        ),
    ]
