# Generated by Django 3.2.12 on 2022-04-14 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='filename_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
