# Generated by Django 3.2.12 on 2022-04-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_alter_ingredient_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity_unit',
            field=models.CharField(default='0000000', max_length=80, null=True),
        ),
    ]
